FROM python:3.9-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install tcsh
RUN apt-get -y install gawk
COPY . /app/

RUN pip install -r requirements.txt

RUN mkdir /app/temp
EXPOSE 8000
CMD ["python3", "main.py", "--port=8000"]

